sudo: false
os: linux
dist: bionic

language: python
python: 3.7

addons:
  apt:
     packages:
     - gfortran
     - libblas-dev
     - liblapack-dev
     - ninja-build
  homebrew:
     update: true
     packages:
     - gcc
     - lapack
     - ninja

matrix:
  include:
  - os: osx
    env: FC=gfortran
    language: minimal
    python: 3.7

install:
  - pip3 install meson

script:
  - meson build
  - ninja -C _build test
