name = "s-dftd3"
version = "1.2.1"
license = "LGPL-3.0-or-later"
maintainer = ["@awvwgk"]
author = ["Sebastian Ehlert"]
copyright = "2019-2022 Sebastian Ehlert"
description = "Simple reimplementation of the DFT-D3 method"
keywords = ["dispersion-correction", "quantum-chemistry"]

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"
mctc-lib.tag = "v0.5.1"

[dev-dependencies]
mstore.git = "https://github.com/grimme-lab/mstore"
mstore.tag = "v0.3.0"

[build]
auto-tests = false

[[executable]]
name = "s-dftd3"
dependencies.toml-f.git = "https://github.com/toml-f/toml-f"
dependencies.toml-f.tag = "v0.4.3"

[[test]]
name = "tester"
source-dir = "test/unit"

[[test]]
name = "api-tester"
source-dir = "test/api"
main = "api-test.c"
