[build-system]
requires = ["meson-python", "cffi", "setuptools"]
build-backend = "mesonpy"

[project]
name = "dftd3"
version = "1.1.1"
description = "Python API of the DFT-D3 project"
readme = "README.rst"
license.text = "LGPL-3.0-or-later"
urls.repository = "https://github.com/dftd3/simple-dftd3"
urls.documentation = "https://dftd3.readthedocs.io"
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Fortran",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.7"
dependencies = [
   "cffi",
   "numpy",
]
optional-dependencies.ase = ["ase"]
optional-dependencies.qcschema = ["qcelemental"]
optional-dependencies.pyscf = ["pyscf"]
optional-dependencies.test = [
  "pytest",
  "pytest-cov",
]
